server:
  port: 8080
spring:
  application:
    name: rims-api
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=RIMS_DB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
jwt:
  signerKey: Bkvw045nqvIXbwCtsf9fNAH8olxBeipB

vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: D90AVGT4
  hash-secret: K59NG1LQGULO1QPDG2LU6BO3YU41XDLJ
  version: 2.1.0
  command: pay
