-- =========================================================================
-- RIMS — lược đồ cơ sở dữ liệu (PostgreSQL)
-- =========================================================================
--
-- File này là NGUỒN THẬT của lược đồ. Hibernate chỉ còn đối chiếu
-- (ddl-auto: validate), không tự tạo và không tự sửa bảng.
--
-- VÌ SAO KHÔNG DÙNG ddl-auto: update: nó im lặng bỏ qua những thay đổi nó
-- không làm được. Đợt thêm cột must_change_password là ví dụ: cơ sở dữ liệu
-- từ chối thêm cột NOT NULL vào bảng đã có dòng khi không kèm DEFAULT,
-- Hibernate ghi một dòng WARN rồi đi tiếp, ứng dụng khởi động bình thường, và
-- mọi truy vấn bảng users đều lỗi. Với validate thì ứng dụng dừng ngay lúc
-- khởi động và nói rõ chỗ lệch.
--
-- Nội dung dưới đây SINH TỪ CHÍNH CÁC ENTITY (jakarta.persistence
-- schema-generation, dialect PostgreSQL). Không gõ tay danh sách cột, nên
-- không thể lệch với entity. Cách sinh lại:
--   mvnw spring-boot:run -Dspring-boot.run.arguments="\
--     --spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect \
--     --spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/pg-schema.sql \
--     --spring.sql.init.mode=never --spring.jpa.hibernate.ddl-auto=none"
-- rồi bọc lại theo đúng dạng dưới đây. Chỉ có hai việc phải làm tay, đều máy
-- móc và dễ soát:
--   1. thêm "if not exists" vào mỗi câu create;
--   2. gộp các câu "alter table ... add constraint FK<băm>" vào trong chính
--      câu create table, và đặt tên đọc được thay cho tên Hibernate băm ra.
--
-- VÌ SAO GỘP KHOÁ NGOẠI VÀO create table: PostgreSQL không có
-- "ALTER TABLE ... ADD CONSTRAINT IF NOT EXISTS", nên một câu ALTER rời sẽ lỗi
-- ở lần khởi động thứ hai. Viết trong create table thì "if not exists" của
-- chính câu đó lo luôn phần idempotent. Đổi lại, THỨ TỰ BẢNG PHẢI ĐÚNG: bảng
-- được trỏ tới phải tạo trước bảng trỏ đến nó. Thứ tự dưới đây đã xếp vậy.
--
-- CHẠY LẠI ĐƯỢC NHIỀU LẦN: mọi câu đều "if not exists", nên khởi động lần thứ
-- hai không lỗi và không mất dữ liệu.
--
-- GIỚI HẠN CẦN BIẾT: "create table if not exists" không sửa bảng đã tồn tại.
-- Trên một cơ sở dữ liệu đã có dữ liệu thật, đổi lược đồ ở đây sẽ KHÔNG có
-- tác dụng — Hibernate validate sẽ dừng ứng dụng và báo lệch, đúng như mong
-- muốn. Lúc đó cần một công cụ di trú (Flyway hoặc Liquibase) chứ không phải
-- thêm câu ALTER vào file này.
--
-- MỖI CÂU PHẢI LÀ MỘT CÂU, VỚI ĐÚNG MỘT DẤU CHẤM PHẨY Ở CUỐI. Spring cắt file
-- theo dấu chấm phẩy rồi gửi từng mảnh sang JDBC, và nó không hiểu cách trích
-- dẫn bằng $$ của PostgreSQL. Vì vậy TUYỆT ĐỐI không viết khối DO $$ ... $$
-- trong file này: dấu chấm phẩy bên trong khối sẽ bị cắt đôi và lỗi cú pháp.
-- Toàn bộ tính idempotent ở đây làm bằng "if not exists", không cần PL/pgSQL.
-- =========================================================================

-- ---------- Bảng không phụ thuộc bảng nào ----------

create table if not exists users (is_active boolean not null, must_change_password boolean default false not null, reward_points integer not null, user_id integer generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, phone varchar(10) not null, role varchar(10) not null check ((role in ('ADMIN','CHEF','WAITER','CASHIER','CUSTOMER'))), email varchar(50) not null, full_name varchar(50) not null, username varchar(50) not null, password_hash varchar(255) not null, primary key (user_id), constraint uk_users_phone unique (phone), constraint uk_users_email unique (email), constraint uk_users_username unique (username));

create table if not exists restaurant_tables (active boolean not null, capacity integer, layout_h integer, layout_w integer, layout_x integer, layout_y integer, table_id integer generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, status varchar(255) check ((status in ('AVAILABLE','RESERVED','SERVING'))), zone varchar(50), table_number varchar(255) not null, primary key (table_id), constraint uk_restaurant_tables_number unique (table_number));

create table if not exists categories (category_id integer generated by default as identity, is_available boolean default true not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, name varchar(50) not null, description varchar(100), primary key (category_id), constraint uk_categories_name unique (name));

create table if not exists restaurant_profile (id integer generated by default as identity, updated_at timestamp(6) not null, phone varchar(30), email varchar(120), name varchar(120) not null, opening_hours varchar(120), address varchar(200), tagline varchar(200), hero_image_url varchar(500), logo_url varchar(500), description varchar(2000), primary key (id));

create table if not exists revoked_tokens (expires_at timestamp(6), revoked_at timestamp(6), jti varchar(255) not null, primary key (jti));

-- ---------- Bảng có khoá ngoại, xếp theo thứ tự phụ thuộc ----------

create table if not exists dishes (category_id integer not null, dish_id integer generated by default as identity, is_available boolean not null, is_hidden boolean not null, price integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, name varchar(50) not null, description varchar(100), image_url varchar(500), primary key (dish_id), constraint uk_dishes_name unique (name), constraint fk_dishes_category foreign key (category_id) references categories);

create table if not exists orders (created_by integer not null, pending_customer_id integer, pending_points_used integer, table_id integer not null, total_amount numeric(38,2) not null, created_at timestamp(6) not null, locked_at timestamp(6), order_id bigint generated by default as identity, status varchar(255) not null check ((status in ('SERVING','LOCKED','COMPLETED'))), primary key (order_id), constraint fk_orders_created_by foreign key (created_by) references users, constraint fk_orders_table foreign key (table_id) references restaurant_tables);

create table if not exists order_items (dish_id integer not null, quantity integer not null, sub_total numeric(38,2) not null, unit_price numeric(38,2) not null, cancel_requested_at timestamp(6), chef_internal_note_acknowledged_at timestamp(6), chef_internal_note_created_at timestamp(6), created_at timestamp(6) not null, order_id bigint not null, order_item_id bigint generated by default as identity, updated_at timestamp(6) not null, dish_name_snapshot varchar(50) not null, cancel_reason varchar(100), chef_internal_note varchar(100), note varchar(100), status varchar(255) not null check ((status in ('PREPARING','COMPLETED','CANCELLED'))), primary key (order_item_id), constraint fk_order_items_dish foreign key (dish_id) references dishes, constraint fk_order_items_order foreign key (order_id) references orders);

create table if not exists invoices (customer_id integer, final_amount numeric(38,2) not null, points_earned_on_invoice integer, points_used_on_invoice integer, restaurant_revenue_amount numeric(38,2), invoice_date timestamp(6) not null, invoice_id bigint generated by default as identity, order_id bigint not null, primary key (invoice_id), constraint uk_invoices_order unique (order_id), constraint fk_invoices_customer foreign key (customer_id) references users, constraint fk_invoices_order foreign key (order_id) references orders);

create table if not exists payments (amount numeric(38,2) not null, is_success boolean not null, invoice_id bigint not null, payment_date timestamp(6) not null, payment_id bigint generated by default as identity, payment_method varchar(255) not null check ((payment_method in ('CASH','QRCODE'))), primary key (payment_id), constraint fk_payments_invoice foreign key (invoice_id) references invoices);

create table if not exists payment_transaction (is_success boolean not null, payment_id bigint not null, transaction_date timestamp(6) not null, transaction_id bigint generated by default as identity, gateway varchar(255), gateway_response text not null, transaction_code varchar(255) not null, primary key (transaction_id), constraint fk_payment_tx_payment foreign key (payment_id) references payments);

create table if not exists reservations (table_id integer, user_id integer, created_at timestamp(6) not null, reservation_id bigint generated by default as identity, reservation_time timestamp(6), updated_at timestamp(6) not null, phone varchar(10) not null, customer_name varchar(50) not null, note varchar(100), status varchar(255) check ((status in ('QUEUED','WAITING','COMPLETED','CANCELLED'))), primary key (reservation_id), constraint fk_reservations_table foreign key (table_id) references restaurant_tables, constraint fk_reservations_user foreign key (user_id) references users);

-- ---------- Chỉ số ----------
--
-- Hibernate sinh tên băm (IDX2leq681r98n...) cho chỉ số này. Đặt tên đọc được
-- vì "create index if not exists" hỏi theo TÊN: tên băm đổi theo tên cột, còn
-- tên dưới đây thì không.

create index if not exists ix_reservations_reservation_time on reservations (reservation_time);

-- ---------- Thêm cột vào bảng đã có ----------
--
-- "create table if not exists" KHÔNG sửa bảng đã tồn tại, nên năm cột mặt
-- bằng ở trên chỉ tới được cơ sở dữ liệu mới. Trên một cơ sở dữ liệu đã chạy,
-- Hibernate validate sẽ dừng ứng dụng vì entity có cột mà bảng thì không.
--
-- PostgreSQL CÓ "add column if not exists" (khác với "add constraint", thứ
-- không có), nên năm câu dưới đây chạy lại được nhiều lần và không mất dữ
-- liệu. Cột để NULL: bàn cũ chưa có chỗ trên sơ đồ, và sơ đồ hiểu NULL là
-- "chưa đặt chỗ" chứ không phải toạ độ (0,0).
--
-- Đây KHÔNG phải công cụ di trú. Khi số thay đổi lược đồ nhiều hơn vài câu
-- thêm cột, dự án cần Flyway hoặc Liquibase chứ không phải kéo dài mục này.

alter table restaurant_tables add column if not exists layout_x integer;

alter table restaurant_tables add column if not exists layout_y integer;

alter table restaurant_tables add column if not exists layout_w integer;

alter table restaurant_tables add column if not exists layout_h integer;

alter table restaurant_tables add column if not exists zone varchar(50);
